### ISSUE TITLE
Banner UI issue on Mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Francine-Theme-Custom-Speed#1]
Bug - Shop button showing on different place on mobile UI.
Exp - Shop button should show on banner on mobile UI.
Ref Link - https://drive.google.com/file/d/1vVlvx3EUZ15uC7u-VpSRaD3uxD6FZ05R/view

**Comment by ui-amankumar** [comment]
that is banner @ankitcedcoss

**Comment by ankitcedcoss** [comment]
@ui-amankumar Sir, But shop button should show on banner and on preview its showing below banner.

**Comment by ui-amankumar** [comment]
@ankitcedcoss
 I aligned the graphic designer for that update you soon

**Comment by ui-amankumar** [comment]
@ankitcedcoss this issue is ready for the test.

**Comment by ankitcedcoss** [comment]
Bug Fixed
